model:
    filters: [32, 32, 64, 64]
    kernel_sizes: [3, 3, 3, 3]
    pool_sizes: [2, 2, 2, 1]
    metrics: ['mse']
    conv_2d_activation: 'relu'
    dense_activation: None
    dense_regularizer: None
    lr: 0.001
    optimizer: 'nadam'
    epochs: 10
    batch_size: 32
    rot_inv: True
    verbose: 0